layout_spectrum: 0
name: "O'Quinn Mountain Village World Community"
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 1
  lightness: 0.7042553
  saturation: 0.812766
  rhythmicContrast: 1
  brandColors:
    - '#00318D'
    - '#8D3819'
    - '#EEDCDC'
    - '#AF8DA5'
    - '#3B64A6'
typography_spectrum: 0.1191489
