layout_spectrum: 0.9361702
typography_spectrum: 0.1191489
color:
  lightness: 0.1638161
  brandStrength: 1
  saturation: 0.2389588
  rhythmicContrast: 0.7382979
  brandColors:
    - '#00318D'
    - '#8D3819'
    - '#EEDCDC'
    - '#AF8DA5'
    - '#3B64A6'
name: "O'Quinn Mountain Village World Community"
